changelog:
  exclude:
    labels:
      - ignore-for-release
      - dependencies
    authors:

  categories:
    - title: Breaking Changes 🛠
      labels:
        - Semver-Major
        - Breaking-Changes
    - title: Bug Fixes
      labels:
        - Semver-Minor
        - Bug-Fixes
    - title: Documentation Update  
      labels:
        - Semver-Minor
        - Documentation
    - title: Exciting New Features 🎉
      labels:
        - Semver-Minor
        - enhancement
    - title: Other Changes
      labels:
        - "*"